-- Clean databse

USE fe;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
TRUNCATE TABLE impuesto;
TRUNCATE TABLE detalle;
TRUNCATE TABLE encabezado;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;